travis:
  secure:
    BINSTAR_TOKEN: n8BDulVLt2tcvZrEZf6KjGkEjDPLuH3X8TEDwXk3GwC+sgi+phWGIFoCm0IYVyiQgt4kqC6JIJkjRmTGTjDDiDcO5ziYunlR+c4R+2Fv1eYiwrX810F6WnUbUktj4PwwwFus4tS1SM+j6+hORxWOD1TvAqu2RqQcLCqJO0gL6Tm/uEMJYw0H7uRkyp2ubm9p2QPcItfJCpTMUoDAfvePJMivQjFFgOLNyEOhI7mMGO/wl5I6kMzlJDsj286OfhL7jmvp6BVfw1qx/F+CUUdyq9Q7Al3dWSanaQ5ZBVcCs1MPzYhGMi5dJezIZSqOHaxC1Jt4MGroE3oAAY+lSyurBwaeKNVO/fzMbOrnsQDn7D9Rr2bh3mFMS1Al0fZ13LkLQ/6Mx78I7uY1hhXNcIpICLNavMvxlgFNVC8Lp4Q2MD94W6uXv4AhndPJebDluExcxgwjdNEMw5Q6SkZON5eIgvHmAK1wXJhNPNMNi3ZZwGZwVFSZqcpY2qZKhNkIs2iY6NTz4VWJyR01k/2/3sXgi5uDqXjR7JiXrXSfVURC6nsHURDMEvLGUw062Xy2tTTY7zLm4UzcUnGv3B/+ckBFm89gnMojbYUNYxJXeE08EhAwDwrI0VO/dMGuJLSX4RJ9McZokpDIQm0PNK5+Q2cA2GMP7mWWkoRkwCJu1DlakKA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
