travis:
  secure:
    BINSTAR_TOKEN: Xc2reEorzQWBFuvnEXy6a0lYwJSZGBLEBNnVe+30cO6Fmb5bB8ySMgrNo+ay88kenOHcxdchQ2NzTX3YGYJ0MTZtCFfIKEF9RiPmIezlbpzxY5hnQsE9GMTpQ69nF6TPp7Ggu99WQ9aETvwUZ6S+Zn9wXl6fMT91HAzlVqwgs5yymIAILtG5bdDaG3adoNRtj1jPxox8wvSKiq50/u7nJlkN51TPQryWs0fz49lCHhevbwIMViiXX4K7M1qtKnV39K6Vzf9t/8lKVYB0HvCXksvQ6yrpY8P+L/KcTYro9PrDMqpa0a7C8kRHVxK8Gk1QYqhKlsxvRVS74b8KevzYphY8g5xKnTQT3ffvj4eV7XVyloEjm75GOyAn25brQMtUc0Btjishi+k/ghr9m0cy+KUot8IWuyU2N+ODIvMCgzDAGATLLGFRYH9+0+YFZCjATwWukRjKJB8uNh2JERLxKxJDQIWDyqdr+y/ubgtUp1F3pSjPFDWyKqqEjPiUnLT/bwfCiczWnSaGS+a+6JJwuozlmytmYlggN6LhZYs9E2BX5txSas9bSrHtFkiHu7pnkxIkvABgQ2G5xa57q6sTX9vDpAudDhtXh3iiDxx7efrkFO71io7LbYCxnJ38ID4xGxYCFQSyABg7EWPSZuCuNU7lnXaF2PfaGWZFMUuhh2Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
