travis:
  secure:
    BINSTAR_TOKEN: sGNxHerGhP8SQnBRplIpbzAhXAaVhL+y0aOmH3Um2sUdcULlFdEmXwr/z8WDr9SxJq2MiqDcxswrms/uhwLzkB2Re4oytXtlh2E2e5W9tL7xjaiL3LoOqc+anbtE1YGRAruql2uWx11NHkfM9KPZ9gF7tSjroAtdfTnxrLDMemrsItQhUMc4fOfQQiJVGlLevgGnt+YPVMvLuWmz5vdVwLJ1Nwp9CcFYyZFqhS63p9iiNHpBVVm82JHRnONxCmYKEmlzj2u5wsOrjCpBl2oAXL2lFKWmxGDgQt0Oo3YEgRcCz0YhIHbQ2qMD6bgsJa2ZQOPh/YB6Tt/us2SJSLIobSheF8aX/RPkfNktW9sCeiqXApdEqUqS9H/QdArgwISbp+gl8S1kgXJtPYzUaqDneKbNDHgAzYPcutDdIyTOlnecPHnSaO9XNBuq0D/tGPKUBLdjYT3WOScioTxcxNIK1qJN89YzrVhQRW1lVWHjE7QGoJvDsB3nSZWi3uZJMI4TfyhpAXpjzFSd61AD4EjYUfSecEmTyz1n5WZBUCcXB3YO+33A3KPSxrtpo1T5/z/0oX5QhVAaTwFBWl7LyjgvdU6R/FEMs6teKyZZaF5modPgyVzR3arAO1Na+iUSJnk86xhlveKQmnXiD35H4sw8jXFUbZiTHqeGxW/mAUj45VU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
